### ISSUE TITLE
  // , Reputation

### ISSUE THREAD

**Issue by v6** [Lunyr/Lunyr#5]
// , Most peer to peer reputation systems work rather poorly, and do not have any strong guarantees against Sybil (botnet/hire accounts of friends) attacks.

Does Lunyr have anything innovative to offer in this? Will Lunyr, in stead, integrate or implement solutions developed elsewhere?
How does such a reputation system avoid ["repstitution"](http://werner.yellowcouch.org/log/why-i-left-stack-overflow-after-6-years/)? 

https://www.civic.com - Startup focused on making conventional authentication accessible via decentralized cryptographic systems

https://blog.openbazaar.org/decentralized-reputation-in-openbazaar/#.WZNMqd_6zCI - OpenBazaar's fairly conventional buyer-seller reputation system

http://archive.is/kTKqG - An example of a highly sophisticated status-brokering reputation system gone awry

These are questions other decentralized systems that require human judgment, like RiskBazaar and OpenBazaar, still struggle with.

**Comment by v6** [comment]
// , Yours.org made a great case against using advertisement for revenue, because of the incentives that such an attention=income system creates.

**Comment by v6** [comment]
// , I don't like to talk about it, but my brief experience with editing Wikipedia left a bad taste in my mouth.

**Comment by arnpham** [comment]
Yes. Please join our Slack channel for all detailed questions.
