### ISSUE TITLE
whitepaper links 404 

### ISSUE THREAD

**Issue by nfriedly** [Lunyr/Lunyr#7]
There are several articles that link to https://github.com/Lunyr/Lunyr/blob/master/Lunyr_White_Paper_ENG.pdf but that's a 404 now. 

Was that removal intentional? Did the file just move to somewhere else? If so, you might want to put a short "placeholder" document there that just explains why and links to your website or the new location.  Otherwise, you're basically throwing away free publicity.

**Comment by nfriedly** [comment]
Oh, it looks like some of your own blog post link to it. For example https://medium.com/lunyr/lunyr-crowdsale-parity-instructions-489b5bb1afbf

**Comment by ConnorChristie** [comment]
You can get to the white paper with this link: https://bravenewcoin.com/assets/Whitepapers/Lunyr-WhitePaper-ENG.pdf
